/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LabAgentPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// ChatView.ts
var import_obsidian = require("obsidian");
var VIEW_TYPE_CHAT = "lab-agent-chat-view";
var ChatView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_CHAT;
  }
  getDisplayText() {
    return "Lab AI Copilot";
  }
  getIcon() {
    return "bot";
  }
  async onOpen() {
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("lab-chat-container");
    this.tabContainer = container.createEl("div", { cls: "lab-tab-header" });
    const tabSync = this.tabContainer.createEl("div", { text: "\u2601\uFE0F \u4E91\u7AEF\u540C\u6B65", cls: "lab-tab active" });
    const tabChat = this.tabContainer.createEl("div", { text: "\u{1F916} AI \u95EE\u7B54", cls: "lab-tab" });
    const tabQA = this.tabContainer.createEl("div", { text: "\u{1F4AC} \u793E\u533A\u89E3\u7B54", cls: "lab-tab" });
    this.syncTabContent = container.createEl("div", { cls: "lab-tab-content active" });
    this.chatTabContent = container.createEl("div", { cls: "lab-tab-content" });
    this.qaTabContent = container.createEl("div", { cls: "lab-tab-content" });
    this.buildSyncTab();
    this.buildChatTab();
    this.buildQATab();
    tabSync.onclick = () => {
      this.switchTab(tabSync, this.syncTabContent);
      this.refreshCloudStatus();
    };
    tabChat.onclick = () => this.switchTab(tabChat, this.chatTabContent);
    tabQA.onclick = () => {
      this.switchTab(tabQA, this.qaTabContent);
      this.refreshQAList();
    };
    this.refreshCloudStatus();
    this.plugin.syncToLabCloud();
    this.refreshQAList();
  }
  switchTab(activeTabEl, activeContentEl) {
    this.tabContainer.querySelectorAll(".lab-tab").forEach((el) => el.removeClass("active"));
    this.syncTabContent.removeClass("active");
    this.chatTabContent.removeClass("active");
    this.qaTabContent.removeClass("active");
    activeTabEl.addClass("active");
    activeContentEl.addClass("active");
  }
  /* =======================================
     SYNC TAB
     ======================================= */
  buildSyncTab() {
    const syncBtn = this.syncTabContent.createEl("button", { text: "\u{1F680} \u4E0A\u4F20\u672C\u5730\u77E5\u8BC6\u5E93\u81F3\u4E91\u7AEF", cls: "lab-big-btn" });
    syncBtn.onclick = async () => {
      syncBtn.disabled = true;
      syncBtn.innerText = "\u4E0A\u4F20\u4E2D...";
      await this.plugin.syncToLabCloud();
      syncBtn.innerText = "\u{1F680} \u4E0A\u4F20\u672C\u5730\u77E5\u8BC6\u5E93\u81F3\u4E91\u7AEF";
      syncBtn.disabled = false;
      this.refreshCloudStatus();
    };
    this.syncTabContent.createEl("h3", { text: "\u8BFE\u9898\u7EC4\u6210\u5458\u4E91\u7AEF\u603B\u5E93\u72B6\u6001" });
    this.cloudStatusContainer = this.syncTabContent.createEl("div", { cls: "lab-cloud-list" });
    this.syncTabContent.createEl("h3", { text: "\u2601\uFE0F \u6211\u7684\u4E91\u7AEF\u77E5\u8BC6\u6811", cls: "lab-tree-title" });
    this.cloudTreeContainer = this.syncTabContent.createEl("div", { cls: "lab-tree-container" });
  }
  async refreshCloudStatus() {
    this.cloudStatusContainer.empty();
    this.cloudStatusContainer.createEl("div", { text: "\u52A0\u8F7D\u4E2D...", cls: "lab-loading-text" });
    try {
      const res = await fetch(`${this.plugin.settings.serverUrl}/api/upload/status`);
      if (!res.ok)
        throw new Error();
      const data = await res.json();
      const members = data.members || [];
      this.cloudStatusContainer.empty();
      if (members.length === 0) {
        this.cloudStatusContainer.createEl("div", { text: "\u76EE\u524D\u4E91\u7AEF\u6570\u636E\u5E93\u4E3A\u7A7A\u3002", cls: "lab-empty-text" });
        return;
      }
      members.forEach((m) => {
        const card = this.cloudStatusContainer.createEl("div", { cls: "lab-member-card" });
        card.createEl("div", { text: `\u{1F464} ${m.username}`, cls: "lab-member-name" });
        card.createEl("div", { text: `\u5DF2\u4E0A\u4F20\u6587\u6863: ${m.total_docs} \u7BC7`, cls: "lab-member-meta" });
        card.createEl("div", { text: `\u6700\u540E\u540C\u6B65: ${m.last_sync}`, cls: "lab-member-meta" });
      });
    } catch (e) {
      this.cloudStatusContainer.empty();
      this.cloudStatusContainer.createEl("div", { text: "\u65E0\u6CD5\u8FDE\u63A5\u5230\u4E91\u7AEF\u670D\u52A1\uFF0C\u8BF7\u68C0\u67E5\u540E\u7AEF\u662F\u5426\u8FD0\u884C\u3002", cls: "lab-error-text" });
    }
    await this.refreshCloudTree();
  }
  async refreshCloudTree() {
    this.cloudTreeContainer.empty();
    this.cloudTreeContainer.createEl("div", { text: "\u6B63\u5728\u62C9\u53D6\u4E91\u7AEF\u7ED3\u6784...", cls: "lab-loading-text" });
    try {
      const res = await fetch(`${this.plugin.settings.serverUrl}/api/upload/tree/${this.plugin.settings.username}`);
      if (!res.ok)
        throw new Error();
      const data = await res.json();
      this.cloudTreeContainer.empty();
      if (!data.tree || data.tree.length === 0) {
        this.cloudTreeContainer.createEl("div", { text: "\u60A8\u7684\u4E91\u7AEF\u6682\u65E0\u6570\u636E\u3002", cls: "lab-empty-text" });
        return;
      }
      this.renderTree(data.tree, this.cloudTreeContainer);
    } catch (e) {
      this.cloudTreeContainer.empty();
      this.cloudTreeContainer.createEl("div", { text: "\u83B7\u53D6\u6811\u72B6\u7ED3\u6784\u5931\u8D25\u3002", cls: "lab-error-text" });
    }
  }
  renderTree(nodes, container, isRoot = true) {
    const ul = container.createEl("ul", { cls: "lab-tree-ul" });
    if (!isRoot) {
      ul.style.display = "none";
    }
    for (const node of nodes) {
      const li = ul.createEl("li", { cls: "lab-tree-li" });
      if (node.type === "folder") {
        const folderDiv = li.createEl("div", { text: `\u25B6 \u{1F4C1} ${node.name}`, cls: "lab-tree-node folder" });
        folderDiv.style.cursor = "pointer";
        let childrenUl = null;
        if (node.children && node.children.length > 0) {
          childrenUl = this.renderTree(node.children, li, false);
        }
        folderDiv.onclick = () => {
          let isExpanded = folderDiv.innerText.startsWith("\u25BC");
          if (!isExpanded) {
            if (childrenUl)
              childrenUl.style.display = "block";
            folderDiv.innerText = `\u25BC \u{1F4C2} ${node.name}`;
          } else {
            if (childrenUl)
              childrenUl.style.display = "none";
            folderDiv.innerText = `\u25B6 \u{1F4C1} ${node.name}`;
          }
        };
      } else {
        li.createEl("div", { text: `\u{1F4C4} ${node.name}`, cls: "lab-tree-node file" });
      }
    }
    return ul;
  }
  updateSessionSelect() {
    if (!this.sessionSelect)
      return;
    this.sessionSelect.empty();
    const sessions = this.plugin.settings.sessions || {};
    const sortedIds = Object.keys(sessions).sort((a, b) => sessions[b].updatedAt - sessions[a].updatedAt);
    for (const id of sortedIds) {
      const s = sessions[id];
      this.sessionSelect.createEl("option", { value: id, text: s.title || "\u65B0\u5BF9\u8BDD" });
    }
    this.sessionSelect.value = this.plugin.settings.sessionId;
  }
  renderCurrentSession() {
    this.messageContainer.empty();
    const session = this.plugin.settings.sessions[this.plugin.settings.sessionId];
    if (session && session.history && session.history.length > 0) {
      for (const msg of session.history) {
        if (msg.role === "ai") {
          this.addMarkdownMessage(msg.content, "ai", this.messageContainer);
        } else {
          this.addMessage(msg.content, "user");
        }
      }
    } else {
      this.addMessage("\u6211\u662F\u8BFE\u9898\u7EC4\u8DE8\u754C\u68C0\u7D22 Agent\u3002\u8BF7\u9009\u62E9\u68C0\u7D22\u8303\u56F4\u540E\u5411\u6211\u63D0\u95EE\u3002", "ai");
    }
  }
  buildChatTab() {
    const header = this.chatTabContent.createEl("div", { cls: "lab-chat-header", attr: { style: "display: flex; gap: 5px; flex-wrap: wrap; align-items: center;" } });
    this.strategySelect = header.createEl("select", { cls: "lab-scope-select lab-strategy-select" });
    this.strategySelect.createEl("option", { value: "agentic", text: "\u{1F9E0} \u4F01\u4E1A\u7EA7\u53CC\u5FAA\u73AF (Agentic RAG)" });
    this.strategySelect.createEl("option", { value: "vector", text: "\u{1F9F2} \u8BED\u4E49\u6A21\u5F0F (Vector RAG)" });
    this.strategySelect.createEl("option", { value: "graph", text: "\u{1F578}\uFE0F \u62D3\u6251\u6A21\u5F0F (Graph RAG)" });
    this.strategySelect.createEl("option", { value: "bm25", text: "\u{1F4DA} \u5B57\u5178\u6A21\u5F0F (BM25 RAG)" });
    this.scopeSelect = header.createEl("select", { cls: "lab-scope-select" });
    this.scopeSelect.createEl("option", { value: "global", text: "\u{1F310} \u5168\u5C40\u77E5\u8BC6\u5E93 (Global)" });
    this.scopeSelect.createEl("option", { value: "\u674E\u5E08\u59D0", text: "\u{1F464} \u674E\u5E08\u59D0\u7684\u7B14\u8BB0" });
    this.scopeSelect.createEl("option", { value: "\u738B\u540C\u5B66", text: "\u{1F464} \u738B\u540C\u5B66\u7684\u7B14\u8BB0" });
    this.scopeSelect.createEl("option", { value: "\u5F20\u540C\u5B66", text: "\u{1F464} \u5F20\u540C\u5B66\u7684\u7B14\u8BB0 (\u81EA\u5DF1)" });
    this.strategySelect.onchange = () => this.retriggerSearch();
    this.scopeSelect.onchange = () => this.retriggerSearch();
    if (!this.plugin.settings.sessions)
      this.plugin.settings.sessions = {};
    this.sessionSelect = header.createEl("select", { cls: "lab-scope-select", attr: { style: "max-width: 120px;" } });
    this.updateSessionSelect();
    this.sessionSelect.onchange = async () => {
      const selectedId = this.sessionSelect.value;
      this.plugin.settings.sessionId = selectedId;
      await this.plugin.saveData(this.plugin.settings);
      this.renderCurrentSession();
    };
    const newChatBtn = header.createEl("button", { text: "\u{1F9F9} \u65B0\u5EFA\u5BF9\u8BDD", cls: "lab-chat-send-btn", attr: { style: "padding: 4px 8px;" } });
    newChatBtn.onclick = async () => {
      const newId = crypto.randomUUID();
      this.plugin.settings.sessionId = newId;
      this.plugin.settings.sessions[newId] = { title: "\u65B0\u5BF9\u8BDD", updatedAt: Date.now(), history: [] };
      await this.plugin.saveData(this.plugin.settings);
      this.updateSessionSelect();
      this.renderCurrentSession();
      this.addMessage("\u6211\u662F\u8BFE\u9898\u7EC4\u8DE8\u754C\u68C0\u7D22 Agent\u3002\u540E\u7AEF\u539F\u751F\u8BB0\u5FC6\u5DF2\u5237\u65B0\uFF0C\u8BF7\u5F00\u542F\u65B0\u7684\u5BF9\u8BDD\u3002", "ai");
    };
    this.messageContainer = this.chatTabContent.createEl("div", { cls: "lab-chat-messages" });
    if (!this.plugin.settings.sessionId || !this.plugin.settings.sessions[this.plugin.settings.sessionId]) {
      const newId = crypto.randomUUID();
      this.plugin.settings.sessionId = newId;
      this.plugin.settings.sessions[newId] = { title: "\u65B0\u5BF9\u8BDD", updatedAt: Date.now(), history: this.plugin.settings.chatHistory || [] };
      this.plugin.saveData(this.plugin.settings);
      this.updateSessionSelect();
    }
    this.renderCurrentSession();
    const inputContainer = this.chatTabContent.createEl("div", { cls: "lab-chat-input-container" });
    this.inputEl = inputContainer.createEl("textarea", { cls: "lab-chat-input" });
    this.inputEl.placeholder = "\u5411\u77E5\u8BC6\u5E93\u63D0\u95EE...";
    this.inputEl.addEventListener("keydown", (e) => {
      if (e.key === "Enter" && !e.shiftKey) {
        e.preventDefault();
        this.sendMessage();
      }
    });
    this.sendBtn = inputContainer.createEl("button", { text: "\u53D1\u9001", cls: "lab-chat-send-btn" });
    this.sendBtn.onclick = () => this.sendMessage();
  }
  async retriggerSearch() {
    if (this.sendBtn.disabled)
      return;
    const session = this.plugin.settings.sessions[this.plugin.settings.sessionId];
    if (!session || !session.history || session.history.length === 0)
      return;
    let lastUserMsg = "";
    for (let i = session.history.length - 1; i >= 0; i--) {
      if (session.history[i].role === "user") {
        lastUserMsg = session.history[i].content;
        break;
      }
    }
    if (!lastUserMsg)
      return;
    this.inputEl.value = lastUserMsg;
    this.sendMessage();
  }
  async sendMessage() {
    const text = this.inputEl.value.trim();
    if (!text)
      return;
    this.inputEl.value = "";
    const scope = this.scopeSelect.value;
    this.addMessage(text, "user");
    const session = this.plugin.settings.sessions[this.plugin.settings.sessionId];
    if (session) {
      session.history.push({ role: "user", content: text });
      if (session.history.length === 1) {
        session.title = text.substring(0, 10) + (text.length > 10 ? "..." : "");
        this.updateSessionSelect();
      }
    }
    await this.plugin.saveData(this.plugin.settings);
    this.inputEl.disabled = true;
    this.sendBtn.disabled = true;
    const loadingId = this.addLoadingIndicator(this.messageContainer);
    try {
      const res = await fetch(`${this.plugin.settings.serverUrl}/api/ai/chat`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          query: text,
          scope,
          strategy: this.strategySelect.value,
          session_id: this.plugin.settings.sessionId
        })
      });
      if (!res.ok)
        throw new Error(`Server returned ${res.status}`);
      const data = await res.json();
      const answer = data.reply || data.answer || data.result || "\u62B1\u6B49\uFF0C\u540E\u7AEF\u672A\u80FD\u8FD4\u56DE\u6709\u6548\u5185\u5BB9\u3002";
      this.removeLoadingIndicator(this.messageContainer, loadingId);
      try {
        await this.addMarkdownMessage(answer, "ai", this.messageContainer);
      } catch (renderError) {
        const msgEl = this.messageContainer.createEl("div", { cls: "lab-chat-message ai" });
        msgEl.innerText = answer;
        this.scrollToBottom(this.messageContainer);
      }
      const session2 = this.plugin.settings.sessions[this.plugin.settings.sessionId];
      if (session2) {
        session2.history.push({ role: "ai", content: answer });
      }
      await this.plugin.saveData(this.plugin.settings);
    } catch (err) {
      this.removeLoadingIndicator(this.messageContainer, loadingId);
      this.addMessage(`\u26A0\uFE0F \u7F51\u7EDC\u8BF7\u6C42\u9519\u8BEF: ${err.message}`, "ai");
    } finally {
      this.inputEl.disabled = false;
      this.sendBtn.disabled = false;
      this.inputEl.focus();
    }
  }
  /* =======================================
     Q&A TAB
     ======================================= */
  buildQATab() {
    const inputContainer = this.qaTabContent.createEl("div", { cls: "lab-qa-input-container" });
    this.qaInputEl = inputContainer.createEl("textarea", { cls: "lab-chat-input" });
    this.qaInputEl.placeholder = "\u9047\u5230\u5B66\u672F\u95EE\u9898\uFF1F\u5411\u5BFC\u5E08\u548C\u5168\u7EC4\u63D0\u95EE...";
    this.qaSubmitBtn = inputContainer.createEl("button", { text: "\u53D1\u5E03\u95EE\u9898", cls: "lab-chat-send-btn" });
    this.qaSubmitBtn.onclick = () => this.submitQA();
    this.qaTabContent.createEl("hr");
    this.qaTabContent.createEl("h3", { text: "\u793E\u533A\u95EE\u7B54\u6D41" });
    this.qaListContainer = this.qaTabContent.createEl("div", { cls: "lab-qa-list" });
  }
  async refreshQAList() {
    this.qaListContainer.empty();
    this.qaListContainer.createEl("div", { text: "\u52A0\u8F7D\u4E2D...", cls: "lab-loading-text" });
    try {
      const res = await fetch(`${this.plugin.settings.serverUrl}/api/ai/server/qa`);
      if (!res.ok)
        throw new Error();
      const data = await res.json();
      const qaList = data.qa_list || [];
      this.qaListContainer.empty();
      if (qaList.length === 0) {
        this.qaListContainer.createEl("div", { text: "\u6682\u65E0\u793E\u533A\u63D0\u95EE\u3002", cls: "lab-empty-text" });
        return;
      }
      for (const qa of qaList) {
        const card = this.qaListContainer.createEl("div", { cls: "lab-qa-card", attr: { style: "position: relative;" } });
        const header = card.createEl("div", { attr: { style: "display: flex; justify-content: space-between; align-items: flex-start;" } });
        header.createEl("div", { text: `\u2753 [${qa.student_name}] ${qa.question}`, cls: "lab-qa-q", attr: { style: "flex-grow: 1;" } });
        if (qa.student_name === this.plugin.settings.username) {
          const delQBtn = header.createEl("button", { text: "\u{1F5D1}\uFE0F \u5220\u9664", cls: "lab-chat-send-btn", attr: { style: "background-color: var(--text-error); margin-left: 10px; padding: 2px 5px; height: 24px; font-size: 0.8em;" } });
          delQBtn.onclick = async () => {
            try {
              const res2 = await fetch(`${this.plugin.settings.serverUrl}/api/ai/server/qa/delete`, {
                method: "DELETE",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ qa_id: qa.id, username: this.plugin.settings.username })
              });
              if (res2.ok) {
                new import_obsidian.Notice("\u95EE\u9898\u5DF2\u5220\u9664");
                this.refreshQAList();
              }
            } catch (e) {
              new import_obsidian.Notice("\u5220\u9664\u5931\u8D25");
            }
          };
        }
        const replies = qa.replies || [];
        if (replies.length > 0) {
          for (const rep of replies) {
            const repRow = card.createEl("div", { attr: { style: "display: flex; justify-content: space-between; align-items: flex-start; margin-top: 5px;" } });
            const repEl = repRow.createEl("div", { cls: "lab-qa-a", attr: { style: "flex-grow: 1; margin-top: 0;" } });
            import_obsidian.MarkdownRenderer.renderMarkdown(`**${rep.author}:** ${rep.content}`, repEl, "", this.plugin);
            if (rep.author === this.plugin.settings.username) {
              const delRBtn = repRow.createEl("button", { text: "\u64A4\u56DE", cls: "lab-chat-send-btn", attr: { style: "background-color: var(--text-muted); margin-left: 10px; padding: 2px 5px; height: 24px; font-size: 0.8em;" } });
              delRBtn.onclick = async () => {
                try {
                  const res2 = await fetch(`${this.plugin.settings.serverUrl}/api/ai/server/qa/reply/delete`, {
                    method: "DELETE",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({ qa_id: qa.id, reply_id: rep.id, username: this.plugin.settings.username })
                  });
                  if (res2.ok) {
                    new import_obsidian.Notice("\u56DE\u590D\u5DF2\u64A4\u56DE");
                    this.refreshQAList();
                  }
                } catch (e) {
                  new import_obsidian.Notice("\u64A4\u56DE\u5931\u8D25");
                }
              };
            }
          }
        } else {
          card.createEl("div", { text: "\u7B49\u5F85\u5BFC\u5E08\u3001\u5E08\u5144\u6216\u8BFE\u9898\u7EC4\u5176\u4ED6\u6210\u5458\u89E3\u7B54...", cls: "lab-qa-pending" });
        }
        card.createEl("div", { text: qa.created_at, cls: "lab-qa-time" });
        const replyDiv = card.createEl("div", { cls: "lab-qa-reply-box", attr: { style: "margin-top: 10px; display: flex; gap: 5px;" } });
        const replyInput = replyDiv.createEl("input", { type: "text", placeholder: "\u5199\u4E0B\u4F60\u7684\u89E3\u7B54...", cls: "lab-chat-input", attr: { style: "flex-grow: 1; height: 30px;" } });
        const replyBtn = replyDiv.createEl("button", { text: "\u56DE\u590D", cls: "lab-chat-send-btn", attr: { style: "height: 30px; padding: 0 10px;" } });
        replyBtn.onclick = async () => {
          const txt = replyInput.value.trim();
          if (!txt)
            return;
          replyBtn.disabled = true;
          try {
            const res2 = await fetch(`${this.plugin.settings.serverUrl}/api/ai/server/qa/reply`, {
              method: "POST",
              headers: { "Content-Type": "application/json" },
              body: JSON.stringify({
                qa_id: qa.id,
                author_name: this.plugin.settings.username,
                reply_text: txt
              })
            });
            if (res2.ok) {
              new import_obsidian.Notice("\u56DE\u590D\u6210\u529F\uFF01");
              this.refreshQAList();
            }
          } catch (e) {
            new import_obsidian.Notice("\u56DE\u590D\u5931\u8D25\uFF0C\u8BF7\u68C0\u67E5\u7F51\u7EDC\u3002");
          } finally {
            replyBtn.disabled = false;
          }
        };
      }
    } catch (e) {
      this.qaListContainer.empty();
      this.qaListContainer.createEl("div", { text: "\u62C9\u53D6\u793E\u533A\u6570\u636E\u5931\u8D25\u3002", cls: "lab-error-text" });
    }
  }
  async submitQA() {
    const text = this.qaInputEl.value.trim();
    if (!text)
      return;
    this.qaInputEl.disabled = true;
    this.qaSubmitBtn.disabled = true;
    try {
      const res = await fetch(`${this.plugin.settings.serverUrl}/api/ai/server/qa/submit`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          student_name: this.plugin.settings.username,
          question: text
        })
      });
      if (res.ok) {
        new import_obsidian.Notice("\u95EE\u9898\u5DF2\u53D1\u5E03\u81F3\u793E\u533A\uFF01");
        this.qaInputEl.value = "";
        this.refreshQAList();
      }
    } catch (e) {
      new import_obsidian.Notice("\u53D1\u5E03\u5931\u8D25\uFF0C\u8BF7\u68C0\u67E5\u7F51\u7EDC\u3002");
    } finally {
      this.qaInputEl.disabled = false;
      this.qaSubmitBtn.disabled = false;
    }
  }
  /* =======================================
     HELPERS
     ======================================= */
  addMessage(text, role) {
    const msgEl = this.messageContainer.createEl("div", { cls: `lab-chat-message ${role}` });
    msgEl.innerText = text;
    this.scrollToBottom(this.messageContainer);
  }
  async addMarkdownMessage(markdownText, role, container) {
    const msgEl = container.createEl("div", { cls: `lab-chat-message ${role}` });
    await import_obsidian.MarkdownRenderer.renderMarkdown(markdownText, msgEl, "", this.plugin);
    this.scrollToBottom(container);
  }
  addLoadingIndicator(container) {
    const id = "loading-" + Date.now();
    const msgEl = container.createEl("div", { cls: "lab-chat-message ai", attr: { id } });
    const dots = msgEl.createEl("div", { cls: "lab-typing-indicator" });
    dots.createEl("div", { cls: "lab-typing-dot" });
    dots.createEl("div", { cls: "lab-typing-dot" });
    dots.createEl("div", { cls: "lab-typing-dot" });
    this.scrollToBottom(container);
    return id;
  }
  removeLoadingIndicator(container, id) {
    const el = container.querySelector(`#${id}`);
    if (el)
      el.remove();
  }
  scrollToBottom(container) {
    setTimeout(() => {
      container.scrollTop = container.scrollHeight;
    }, 50);
  }
};

// main.ts
var DEFAULT_SETTINGS = {
  serverUrl: "http://127.0.0.1:8000",
  username: "\u5F20\u540C\u5B66",
  chatHistory: [],
  sessionId: "",
  sessions: {}
};
var LabAgentPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(
      VIEW_TYPE_CHAT,
      (leaf) => new ChatView(leaf, this)
    );
    const ribbonIconEl = this.addRibbonIcon("bot", "Lab AI Copilot", (evt) => {
      this.activateView();
    });
    ribbonIconEl.addClass("lab-agent-ribbon-class");
    this.addCommand({
      id: "open-lab-chat-view",
      name: "Open Lab AI Copilot",
      callback: () => {
        this.activateView();
      }
    });
    this.addCommand({
      id: "sync-to-lab-cloud",
      name: "Sync to Lab Cloud",
      callback: async () => {
        await this.syncToLabCloud();
      }
    });
    this.addSettingTab(new LabAgentSettingTab(this.app, this));
  }
  onunload() {
    this.app.workspace.detachLeavesOfType(VIEW_TYPE_CHAT);
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE_CHAT);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      await (leaf == null ? void 0 : leaf.setViewState({ type: VIEW_TYPE_CHAT, active: true }));
    }
    if (leaf) {
      workspace.revealLeaf(leaf);
    }
  }
  async syncToLabCloud() {
    new import_obsidian2.Notice("Starting sync to Lab Cloud...");
    const allItems = this.app.vault.getAllLoadedFiles();
    const files = allItems.filter((f) => f instanceof import_obsidian2.TFile && f.extension === "md");
    const folders = allItems.filter((f) => f instanceof import_obsidian2.TFolder && f.path !== "/");
    let successCount = 0;
    let failCount = 0;
    for (const folder of folders) {
      await this.uploadFolder(folder);
    }
    const limit = 5;
    let active = 0;
    let index = 0;
    return new Promise((resolve) => {
      const next = async () => {
        if (index >= files.length && active === 0) {
          new import_obsidian2.Notice(`Sync complete: ${successCount} files succeeded, ${failCount} failed.`);
          resolve();
          return;
        }
        while (active < limit && index < files.length) {
          const file = files[index++];
          active++;
          this.uploadFile(file).then((success) => {
            if (success)
              successCount++;
            else
              failCount++;
          }).catch(() => {
            failCount++;
          }).finally(() => {
            active--;
            next();
          });
        }
      };
      next();
    });
  }
  async uploadFolder(folder) {
    try {
      const response = await fetch(`${this.settings.serverUrl}/api/upload/folder`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          username: this.settings.username,
          foldername: folder.path
        })
      });
      return response.ok;
    } catch (e) {
      return false;
    }
  }
  async uploadFile(file) {
    try {
      const content = await this.app.vault.read(file);
      const payload = {
        username: this.settings.username,
        filename: file.path,
        content
      };
      const response = await fetch(`${this.settings.serverUrl}/api/upload`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload)
      });
      return response.ok;
    } catch (e) {
      console.error(`Failed to upload ${file.name}:`, e);
      return false;
    }
  }
};
var LabAgentSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian2.Setting(containerEl).setName("Server URL").setDesc("API Endpoint of the agent-service").addText((text) => text.setPlaceholder("http://127.0.0.1:8000").setValue(this.plugin.settings.serverUrl).onChange(async (value) => {
      this.plugin.settings.serverUrl = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName("Username").setDesc("Your identity in the Lab Knowledge Base").addText((text) => text.setPlaceholder("\u5F20\u540C\u5B66").setValue(this.plugin.settings.username).onChange(async (value) => {
      this.plugin.settings.username = value;
      await this.plugin.saveSettings();
    }));
  }
};
